sudo: required

language: ruby

services:
  - docker

env:
  DOCKER_NAME: paritokio-mongo

before_install:
  - docker build -t $DOCKER_NAME .
  - docker run --name $DOCKER_NAME -d mongo
  - docker ps -a
#  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" 62.210.107.5:5000

script: 
  - docker push 62.210.107.5:5000 $DOCKER_NAME

