sudo: required

language: ruby

services:
  - docker

env:
  DOCKER_NAME: paritokio-mongo
  DOCKER_REGISTRY: registry.paritokio.com:5000

before_install:
  - docker build -t $DOCKER_NAME .
  - docker run --name $DOCKER_NAME -d mongo
  - docker ps -a
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" $DOCKER_REGISTRY

script: 
  - docker tag $DOCKER_NAME $DOCKER_REGISTRY/$DOCKER_NAME
  - docker push $DOCKER_REGISTRY/$DOCKER_NAME

